name: Deploy Server to Render

on:
  push:
    branches: [main]
    paths: ['server/**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Check
        run: |
          cd server
          npm install